name: Build AzNamingTool and push to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: microsoft/CloudAdoptionFramework
          path: "./"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          file: ready/AzNamingTool/Dockerfile
          context: ./ready/AzNamingTool
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:latest
          labels: ${{ steps.meta.outputs.labels }}
